In [1]:
import numpy as np

#Problem 1
Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes

In [7]:
one_d = np.array([1,2,4,56])
print(one_d.ndim)
print(one_d.shape)
print(one_d)

1
(4,)
[ 1  2  4 56]

In [8]:
two_d = np.array(
    [
         [1,2,3,4,5],
    [2,3,4,6,8]

    ]

)
print(two_d)
print(two_d.ndim)
print(two_d.shape)

[[1 2 3 4 5]
 [2 3 4 6 8]]
2
(2, 5)

In [9]:
three_d = np.array(
    [
        [
    [1,2,3,4,5],
    [2,3,4,6,8]
    ],
    [
        [3,4,5,6,7],
        [3,4,6,8,8]
    ]

    ]

)
print(three_d)
print(three_d.ndim)
print(three_d.shape)

[[[1 2 3 4 5]
  [2 3 4 6 8]]

 [[3 4 5 6 7]
  [3 4 6 8 8]]]
3
(2, 2, 5)

. Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7

In [17]:
zer = np.zeros((3,3))
on = np.ones((2,5))
sev = on*7
seven = np.full((2,4),7)
print(zer)
print(on)
print(sev)
print(seven)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]
[[7 7 7 7]
 [7 7 7 7]]

3 . Create an array of even numbers between 10 and 50 using arange.

In [18]:
ev = np.arange(10,50,2)
print(ev)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]

 . Create a 4×4 matrix from 0–15. Then , extract:
the first row


the last column


a 2×2 subarray from the center

In [23]:
mat = np.arange(0,16).reshape((4,4))
print(mat)
print(mat[0])
print(mat[:,[0]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[[ 0]
 [ 4]
 [ 8]
 [12]]

#Pandas

In [24]:
import pandas as pd

Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [27]:
lst = [10, 20, 30, 40, 50]
df = pd.Series(lst)
print(df)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [28]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
df.dtype

dtype('int64')

In [30]:
dic = {
    "Name" : ["Hridoy","Banik","Akash","Bilota"],
    "Age" : [13,4,5,67],
    "City" : ["Finland","Thermi","Greece","Chattogram"]
}
df = pd.DataFrame(dic)
print(df)

     Name  Age        City
0  Hridoy   13     Finland
1   Banik    4      Thermi
2   Akash    5      Greece
3  Bilota   67  Chattogram

Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [32]:
df.describe()

             Age
count   4.000000
mean   22.250000
std    30.103986
min     4.000000
25%     4.750000
50%     9.000000
75%    26.500000
max    67.000000



Create a DataFrame using the dictionary below:


data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row

In [35]:
data = { 'Product': ['Pen', 'Book', 'Eraser', 'Pencil'], 'Price': [10, 50, 5, 7], 'Quantity': [100, 60, 200, 150] }
df = pd.DataFrame(data)
print(df)

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [36]:
print(df.columns)

Index(['Product', 'Price', 'Quantity'], dtype='object')

In [37]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [40]:
print(df.loc[0])

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [42]:
print(df['Product'])

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [43]:
print(df.loc[:,'Product'])

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

#4. Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [44]:
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [46]:
print(df.loc[0])

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [47]:
print(df.loc[:,'Product'])

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [48]:
print(df.loc[0:2,['Product','Price']])

  Product  Price
0     Pen     10
1    Book     50
2  Eraser      5

In [49]:
print(df.iloc[0])

Product     Pen
Price        10
Quantity    100
Name: 0, dtype: object

In [50]:
print(df.iloc[:,0])

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [54]:
print(df.iloc[0:2,1:3])

   Price  Quantity
0     10       100
1     50        60


# Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index

In [56]:
dict = {
    "Name" : ["AKash","Aninda","Rabin","Priyotosh"],
    "Age" : [23,4,33,45],
    "marks" : [23,44,56,76],
    "grade" :[2,4,5,6]
}
df = pd.DataFrame(dict)
print(df)

        Name  Age  marks  grade
0      AKash   23     23      2
1     Aninda    4     44      4
2      Rabin   33     56      5
3  Priyotosh   45     76      6

In [59]:
df.drop('Name',axis = 1, inplace= True)
print(df)

   Age  marks  grade
0   23     23      2
1    4     44      4
2   33     56      5
3   45     76      6

In [60]:
df.drop(2,inplace = True)
print(df)

   Age  marks  grade
0   23     23      2
1    4     44      4
3   45     76      6

#Create a DataFrame of employees with columns "Name", "Department", and "Salary". Sort it by "Salary" in ascending order and by "Name" in descending order.

In [61]:
dict = {
    "Name" : ["AKash","Aninda","Rabin","Priyotosh"],
    "Dept" : ["Electrical","Civil","Mechanical","Pharmacy"],
    "salary" : [200003,404174,54746,104576]

}
df = pd.DataFrame(dict)
print(df)

        Name        Dept  salary
0      AKash  Electrical  200003
1     Aninda       Civil  404174
2      Rabin  Mechanical   54746
3  Priyotosh    Pharmacy  104576

In [63]:
df.sort_values('salary',inplace = True)
print(df)

        Name        Dept  salary
2      Rabin  Mechanical   54746
3  Priyotosh    Pharmacy  104576
0      AKash  Electrical  200003
1     Aninda       Civil  404174

In [65]:
df.sort_values('Name',inplace = True, ascending = False)
print(df)

        Name        Dept  salary
2      Rabin  Mechanical   54746
3  Priyotosh    Pharmacy  104576
1     Aninda       Civil  404174
0      AKash  Electrical  200003

#Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print students with Score > 60 and those with Score < 40.

In [70]:
student_data = {
    "Name": ["Alex", "Jordan", "Taylor", "Morgan", "Casey", "Riley", "Jamie", "Skyler"],
    "Score": [85, 12, 78, 38, 95, 71, 24, 90]
}
df = pd.DataFrame(student_data)
print(df)

     Name  Score
0    Alex     85
1  Jordan     12
2  Taylor     78
3  Morgan     38
4   Casey     95
5   Riley     71
6   Jamie     24
7  Skyler     90

In [71]:
print(df[df['Score'] > 60] )

     Name  Score
0    Alex     85
2  Taylor     78
4   Casey     95
5   Riley     71
7  Skyler     90

In [72]:
print(df[df['Score'] < 60] )

     Name  Score
1  Jordan     12
3  Morgan     38
6   Jamie     24