In [3]:
import pandas as pd

In [4]:
cs = pd.read_csv('student_data.csv')
print(type(cs))
print(cs)

<class 'pandas.core.frame.DataFrame'>
   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [5]:
ex = pd.read_excel('phitron_student_marks.xlsx')

In [6]:
print(ex)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [7]:
#parquet file
par = pd.read_parquet('students.parquet')
print(type(par))
print(par)

<class 'pandas.core.frame.DataFrame'>
   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [8]:
#JSON file
js = pd.read_json('data.json')
print(type(js))
print(js)

<class 'pandas.core.frame.DataFrame'>
  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82

#Pandas Basic Functionalities

In [9]:
df = pd.read_csv('student_data.csv')
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [10]:
#first 5 values
heads = df.head()
print(heads)

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                  85.0             85.0
1    PH1002     Fatima Akhter                  92.0             92.0
2    PH1003     Imran Hossain                  88.0             88.0
3    PH1004  Jannatul Ferdous                  78.0             78.0
4    PH1005       Kamal Uddin                   NaN              NaN

   Python Marks CompletionStatus EnrollmentDate Instructor    Location
0          88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1           NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2          85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3          82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4          95.0      In Progress     2024-03-05  Mr. Karim  Chattogram

In [11]:
lasts = df.tail()
print(lasts)

   StudentID      FullName  Data Structure Marks  Algorithm Marks  \
15    PH1016  Ziaur Rahman                  94.0             94.0
16    PH1017   Afsana Mimi                  90.0             90.0
17    PH1018   Babul Ahmed                  88.0             88.0
18    PH1019  Faria Rahman                   NaN              NaN
19    PH1020    Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [12]:
#columns
print(df.columns)

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

In [13]:
cols = list(df.columns)
print(cols)

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location']

In [14]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [15]:
import numpy as np

In [16]:
ind = np.array(df.index)
print(ind)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [17]:
df = pd.read_csv('student_data.csv')

In [18]:
#column
cls = df.columns
lst = list(cls) #column to list conversion
print(lst)

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location']

In [19]:
#index
print(df.index)

RangeIndex(start=0, stop=20, step=1)

In [20]:
df.index
ind = np.array(df.index)
print(ind)
print(ind.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [22]:
df.sample(10) # to get the random value of any dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka

In [23]:
df.describe() #to find out statistical value

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

In [24]:
#list to dataset

my_list = [['Hridoy', 27], ['Bilota',35], ['Harami', 85]]
df = pd.DataFrame(my_list,columns=['Name','Age'])
print(df)
print(type(df))

     Name  Age
0  Hridoy   27
1  Bilota   35
2  Harami   85
<class 'pandas.core.frame.DataFrame'>

In [25]:
#tuple to dataset
my_tuple = (("Hridoy",35),("Bilota",23),("Kohli",39))
df = pd.DataFrame(my_tuple,columns = ['Name','Age'])
print(df)

     Name  Age
0  Hridoy   35
1  Bilota   23
2   Kohli   39

In [26]:
my_dict = {
    'Name' : ["Hridoy","Banik","Akash"],
    'Age' : [25,95,110]
}
df = pd.DataFrame(my_dict)
print(df)

     Name  Age
0  Hridoy   25
1   Banik   95
2   Akash  110

In [27]:
df = pd.read_csv('student_data.csv')
#accessing a column
df['FullName']
print(type(df['FullName']))

<class 'pandas.core.series.Series'>

In [28]:
#loc[row(index),column(features)]
#df.loc[row_start:row_end, col_start: col_end]
df.loc[0]
print(type(df.loc[0]))

<class 'pandas.core.series.Series'>

In [29]:
#multiple row (normal list)
df.loc[[2,3,19]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [30]:
#multiple row (By using range)
df.loc[2:8]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka

In [31]:
#single column
df.loc[:,'Python Marks']

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

In [32]:
#multiple column
df.loc[:,['Python Marks',"Algorithm Marks"]]

    Python Marks  Algorithm Marks
0           88.0             85.0
1            NaN             92.0
2           85.0             88.0
3           82.0             78.0
4           95.0              NaN
5           78.0             75.0
6            NaN             80.0
7           85.0             81.0
8           76.0             72.0
9           88.0             89.0
10          91.0              NaN
11          87.0             85.0
12          79.0             75.0
13           NaN              NaN
14          84.0             86.0
15           NaN             94.0
16          93.0             90.0
17          85.0             88.0
18           NaN              NaN
19          89.0             86.0

In [33]:
#row with columns
df.loc[2:6,['Python Marks','Algorithm Marks']]

   Python Marks  Algorithm Marks
2          85.0             88.0
3          82.0             78.0
4          95.0              NaN
5          78.0             75.0
6           NaN             80.0

In [37]:
#iloc
#changing index and columns and iloc
df.set_index('StudentID')

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [38]:
df_index = df.set_index('StudentID')
print(df_index)

                   FullName  Data Structure Marks  Algorithm Marks  \
StudentID
PH1001          Alif Rahman                  85.0             85.0
PH1002        Fatima Akhter                  92.0             92.0
PH1003        Imran Hossain                  88.0             88.0
PH1004     Jannatul Ferdous                  78.0             78.0
PH1005          Kamal Uddin                   NaN              NaN
PH1006          Laila Begum                  75.0             75.0
PH1007       Mahmudul Hasan                  80.0             80.0
PH1008          Nadia Islam                  81.0             81.0
PH1009           Omar Faruq                  72.0             72.0
PH1010         Priya Sharma                  89.0             89.0
PH1011         Rahim Sheikh                   NaN              NaN
PH1012      Sadia Chowdhury                  85.0             85.0
PH1013         Tanvir Ahmed                  75.0             75.0
PH1014           Urmi Akter                   NaN              NaN
PH1015         Wahiduzzaman                  86.0             86.0
PH1016         Ziaur Rahman                  94.0             94.0
PH1017          Afsana Mimi                  90.0             90.0
PH1018          Babul Ahmed                  88.0             88.0
PH1019         Faria Rahman                   NaN              NaN
PH1020           Nasir Khan                  86.0             86.0

           Python Marks CompletionStatus EnrollmentDate Instructor    Location
StudentID
PH1001             88.0        Completed     2024-01-15  Mr. Karim       Dhaka
PH1002              NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
PH1003             85.0        Completed     2024-02-10  Mr. Karim       Dhaka
PH1004             82.0        Completed     2024-02-12  Ms. Salma      Sylhet
PH1005             95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
PH1006             78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
PH1007              NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
PH1008             85.0        Completed     2024-04-22  Ms. Salma  Chattogram
PH1009             76.0        Completed     2024-05-16  Mr. David       Dhaka
PH1010             88.0        Completed     2024-05-20  Ms. Salma      Sylhet
PH1011             91.0      In Progress     2024-06-11  Mr. Karim      Khulna
PH1012             87.0        Completed     2024-06-14  Ms. Salma  Chattogram
PH1013             79.0        Completed     2024-07-02  Mr. David       Dhaka
PH1014              NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
PH1015             84.0        Completed     2024-08-18  Mr. Karim       Dhaka
PH1016              NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
PH1017             93.0        Completed     2025-09-01  Mr. Karim       Dhaka
PH1018             85.0        Completed     2025-09-05  Ms. Salma      Sylhet
PH1019              NaN      Not Started     2025-09-15  Mr. David  Chattogram
PH1020             89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [43]:
df_index.iloc[:,1:4]

           Data Structure Marks  Algorithm Marks  Python Marks
StudentID
PH1001                     85.0             85.0          88.0
PH1002                     92.0             92.0           NaN
PH1003                     88.0             88.0          85.0
PH1004                     78.0             78.0          82.0
PH1005                      NaN              NaN          95.0
PH1006                     75.0             75.0          78.0
PH1007                     80.0             80.0           NaN
PH1008                     81.0             81.0          85.0
PH1009                     72.0             72.0          76.0
PH1010                     89.0             89.0          88.0
PH1011                      NaN              NaN          91.0
PH1012                     85.0             85.0          87.0
PH1013                     75.0             75.0          79.0
PH1014                      NaN              NaN           NaN
PH1015                     86.0             86.0          84.0
PH1016                     94.0             94.0           NaN
PH1017                     90.0             90.0          93.0
PH1018                     88.0             88.0          85.0
PH1019                      NaN              NaN           NaN
PH1020                     86.0             86.0          89.0

In [48]:
df.rename(columns={'FullName': 'Full Name','Algorithm Marks': 'Algo Marks'})

,StudentID,Full Name,Data Structure Marks,Algo Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [49]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [50]:
df.drop(0,inplace= True)

In [51]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [53]:
df.drop('Instructor',axis = 1, inplace = True)

In [54]:
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate    Location
1            NaN      In Progress     2024-01-20  Chattogram
2           85.0        Completed     2024-02-10       Dhaka
3           82.0        Completed     2024-02-12      Sylhet
4           95.0      In Progress     2024-03-05  Chattogram
5           78.0        Completed     2024-03-08    Rajshahi
6            NaN      In Progress     2024-04-01       Dhaka
7           85.0        Completed     2024-04-22  Chattogram
8           76.0        Completed     2024-05-16       Dhaka
9           88.0        Completed     2024-05-20      Sylhet
10          91.0      In Progress     2024-06-11      Khulna
11          87.0        Completed     2024-06-14  Chattogram
12          79.0        Completed     2024-07-02       Dhaka
13           NaN      Not Started     2024-07-09    Rajshahi
14          84.0        Completed     2024-08-18       Dhaka
15           NaN      In Progress     2024-08-21  Chattogram
16          93.0        Completed     2025-09-01       Dhaka
17          85.0        Completed     2025-09-05      Sylhet
18           NaN      Not Started     2025-09-15  Chattogram
19          89.0        Completed     2025-10-02       Dhaka

In [60]:
df.loc[1,'Python Marks'] = 95
df.loc[1,'CompletionStatus'] = "Completed"
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
1           95.0        Completed     2024-01-20  Chattogram           95.0
2           85.0        Completed     2024-02-10       Dhaka            NaN
3           82.0        Completed     2024-02-12      Sylhet            NaN
4           95.0      In Progress     2024-03-05  Chattogram            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
6            NaN      In Progress     2024-04-01       Dhaka            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
8           76.0        Completed     2024-05-16       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
10          91.0      In Progress     2024-06-11      Khulna            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
15           NaN      In Progress     2024-08-21  Chattogram            NaN
16          93.0        Completed     2025-09-01       Dhaka            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
0            NaN        Completed            NaN         NaN            NaN

In [62]:
df.loc[1:3,'Python Marks'] += 2
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
1           99.0        Completed     2024-01-20  Chattogram           95.0
2           89.0        Completed     2024-02-10       Dhaka            NaN
3           86.0        Completed     2024-02-12      Sylhet            NaN
4           95.0      In Progress     2024-03-05  Chattogram            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
6            NaN      In Progress     2024-04-01       Dhaka            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
8           76.0        Completed     2024-05-16       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
10          91.0      In Progress     2024-06-11      Khulna            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
15           NaN      In Progress     2024-08-21  Chattogram            NaN
16          93.0        Completed     2025-09-01       Dhaka            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
0            NaN        Completed            NaN         NaN            NaN

In [63]:
for i,series in df.iterrows():
  print(f'{i} : {series}')

1 : StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                     99.0
CompletionStatus            Completed
EnrollmentDate             2024-01-20
Location                   Chattogram
Python Marks                     95.0
Name: 1, dtype: object
2 : StudentID                      PH1003
FullName                Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  88.0
Python Marks                     89.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Location                        Dhaka
Python Marks                      NaN
Name: 2, dtype: object
3 : StudentID                         PH1004
FullName                Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     78.0
Python Marks                        86.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Location                          Sylhet
Python Marks                         NaN
Name: 3, dtype: object
4 : StudentID                    PH1005
FullName                Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   95.0
CompletionStatus        In Progress
EnrollmentDate           2024-03-05
Location                 Chattogram
Python Marks                    NaN
Name: 4, dtype: object
5 : StudentID                    PH1006
FullName                Laila Begum
Data Structure Marks           75.0
Algorithm Marks                75.0
Python Marks                   78.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Location                   Rajshahi
Python Marks                    NaN
Name: 5, dtype: object
6 : StudentID                       PH1007
FullName                Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Location                         Dhaka
Python Marks                       NaN
Name: 6, dtype: object
7 : StudentID                    PH1008
FullName                Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Location                 Chattogram
Python Marks                    NaN
Name: 7, dtype: object
8 : StudentID                   PH1009
FullName                Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  76.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Location                     Dhaka
Python Marks                   NaN
Name: 8, dtype: object
9 : StudentID                     PH1010
FullName                Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    88.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Location                      Sylhet
Python Marks                     NaN
Name: 9, dtype: object
10 : StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Location                      Khulna
Python Marks                     NaN
Name: 10, dtype: object
11 : StudentID                        PH1012
FullName                Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       87.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Location                     Chattogram
Python Marks                        NaN
Name: 11, dtype: object
12 : StudentID                     PH1013
FullName                Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Location                       Dhaka
Python Marks                     NaN
Name: 12, dtype: object
13 : StudentID                    PH1014
FullName                 Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Location                   Rajshahi
Python Marks                    NaN
Name: 13, dtype: object
14 : StudentID                     PH1015
FullName                Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    84.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Location                       Dhaka
Python Marks                     NaN
Name: 14, dtype: object
15 : StudentID                     PH1016
FullName                Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Location                  Chattogram
Python Marks                     NaN
Name: 15, dtype: object
16 : StudentID                    PH1017
FullName                Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   93.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Location                      Dhaka
Python Marks                    NaN
Name: 16, dtype: object
17 : StudentID                    PH1018
FullName                Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Location                     Sylhet
Python Marks                    NaN
Name: 17, dtype: object
18 : StudentID                     PH1019
FullName                Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Location                  Chattogram
Python Marks                     NaN
Name: 18, dtype: object
19 : StudentID                   PH1020
FullName                Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  89.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Location                     Dhaka
Python Marks                   NaN
Name: 19, dtype: object
0 : StudentID                     NaN
FullName                      NaN
Data Structure Marks          NaN
Algorithm Marks               NaN
Python Marks                  NaN
CompletionStatus        Completed
EnrollmentDate                NaN
Location                      NaN
Python Marks                  NaN
Name: 0, dtype: object

In [64]:
for i in df.itertuples():
  print(i)

Pandas(Index=1, StudentID='PH1002', FullName='Fatima Akhter', _3=92.0, _4=92.0, _5=99.0, CompletionStatus='Completed', EnrollmentDate='2024-01-20', Location='Chattogram', _9=95.0)
Pandas(Index=2, StudentID='PH1003', FullName='Imran Hossain', _3=88.0, _4=88.0, _5=89.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Location='Dhaka', _9=nan)
Pandas(Index=3, StudentID='PH1004', FullName='Jannatul Ferdous', _3=78.0, _4=78.0, _5=86.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Location='Sylhet', _9=nan)
Pandas(Index=4, StudentID='PH1005', FullName='Kamal Uddin', _3=nan, _4=nan, _5=95.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Location='Chattogram', _9=nan)
Pandas(Index=5, StudentID='PH1006', FullName='Laila Begum', _3=75.0, _4=75.0, _5=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Location='Rajshahi', _9=nan)
Pandas(Index=6, StudentID='PH1007', FullName='Mahmudul Hasan', _3=80.0, _4=80.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Location='Dhaka', _9=nan)
Pandas(Index=7, StudentID='PH1008', FullName='Nadia Islam', _3=81.0, _4=81.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Location='Chattogram', _9=nan)
Pandas(Index=8, StudentID='PH1009', FullName='Omar Faruq', _3=72.0, _4=72.0, _5=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Location='Dhaka', _9=nan)
Pandas(Index=9, StudentID='PH1010', FullName='Priya Sharma', _3=89.0, _4=89.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Location='Sylhet', _9=nan)
Pandas(Index=10, StudentID='PH1011', FullName='Rahim Sheikh', _3=nan, _4=nan, _5=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Location='Khulna', _9=nan)
Pandas(Index=11, StudentID='PH1012', FullName='Sadia Chowdhury', _3=85.0, _4=85.0, _5=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Location='Chattogram', _9=nan)
Pandas(Index=12, StudentID='PH1013', FullName='Tanvir Ahmed', _3=75.0, _4=75.0, _5=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Location='Dhaka', _9=nan)
Pandas(Index=13, StudentID='PH1014', FullName='Urmi Akter', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Location='Rajshahi', _9=nan)
Pandas(Index=14, StudentID='PH1015', FullName='Wahiduzzaman', _3=86.0, _4=86.0, _5=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Location='Dhaka', _9=nan)
Pandas(Index=15, StudentID='PH1016', FullName='Ziaur Rahman', _3=94.0, _4=94.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Location='Chattogram', _9=nan)
Pandas(Index=16, StudentID='PH1017', FullName='Afsana Mimi', _3=90.0, _4=90.0, _5=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Location='Dhaka', _9=nan)
Pandas(Index=17, StudentID='PH1018', FullName='Babul Ahmed', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Location='Sylhet', _9=nan)
Pandas(Index=18, StudentID='PH1019', FullName='Faria Rahman', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Location='Chattogram', _9=nan)
Pandas(Index=19, StudentID='PH1020', FullName='Nasir Khan', _3=86.0, _4=86.0, _5=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Location='Dhaka', _9=nan)
Pandas(Index=0, StudentID=nan, FullName=nan, _3=nan, _4=nan, _5=nan, CompletionStatus='Completed', EnrollmentDate=nan, Location=nan, _9=nan)

#sorting

In [66]:
copy = df.sort_values('Data Structure Marks')
print(copy)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
8     PH1009        Omar Faruq                  72.0             72.0
5     PH1006       Laila Begum                  75.0             75.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
11    PH1012   Sadia Chowdhury                  85.0             85.0
14    PH1015      Wahiduzzaman                  86.0             86.0
19    PH1020        Nasir Khan                  86.0             86.0
17    PH1018       Babul Ahmed                  88.0             88.0
2     PH1003     Imran Hossain                  88.0             88.0
9     PH1010      Priya Sharma                  89.0             89.0
16    PH1017       Afsana Mimi                  90.0             90.0
1     PH1002     Fatima Akhter                  92.0             92.0
15    PH1016      Ziaur Rahman                  94.0             94.0
4     PH1005       Kamal Uddin                   NaN              NaN
10    PH1011      Rahim Sheikh                   NaN              NaN
13    PH1014        Urmi Akter                   NaN              NaN
18    PH1019      Faria Rahman                   NaN              NaN
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
8           76.0        Completed     2024-05-16       Dhaka            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
3           86.0        Completed     2024-02-12      Sylhet            NaN
6            NaN      In Progress     2024-04-01       Dhaka            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
2           89.0        Completed     2024-02-10       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
16          93.0        Completed     2025-09-01       Dhaka            NaN
1           99.0        Completed     2024-01-20  Chattogram           95.0
15           NaN      In Progress     2024-08-21  Chattogram            NaN
4           95.0      In Progress     2024-03-05  Chattogram            NaN
10          91.0      In Progress     2024-06-11      Khulna            NaN
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN
0            NaN        Completed            NaN         NaN            NaN

In [68]:
cpy = df.sort_values('Data Structure Marks',ascending= False)
print(cpy)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
15    PH1016      Ziaur Rahman                  94.0             94.0
1     PH1002     Fatima Akhter                  92.0             92.0
16    PH1017       Afsana Mimi                  90.0             90.0
9     PH1010      Priya Sharma                  89.0             89.0
17    PH1018       Babul Ahmed                  88.0             88.0
2     PH1003     Imran Hossain                  88.0             88.0
14    PH1015      Wahiduzzaman                  86.0             86.0
19    PH1020        Nasir Khan                  86.0             86.0
11    PH1012   Sadia Chowdhury                  85.0             85.0
7     PH1008       Nadia Islam                  81.0             81.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
5     PH1006       Laila Begum                  75.0             75.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
8     PH1009        Omar Faruq                  72.0             72.0
4     PH1005       Kamal Uddin                   NaN              NaN
10    PH1011      Rahim Sheikh                   NaN              NaN
13    PH1014        Urmi Akter                   NaN              NaN
18    PH1019      Faria Rahman                   NaN              NaN
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
15           NaN      In Progress     2024-08-21  Chattogram            NaN
1           99.0        Completed     2024-01-20  Chattogram           95.0
16          93.0        Completed     2025-09-01       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
2           89.0        Completed     2024-02-10       Dhaka            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
6            NaN      In Progress     2024-04-01       Dhaka            NaN
3           86.0        Completed     2024-02-12      Sylhet            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
8           76.0        Completed     2024-05-16       Dhaka            NaN
4           95.0      In Progress     2024-03-05  Chattogram            NaN
10          91.0      In Progress     2024-06-11      Khulna            NaN
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN
0            NaN        Completed            NaN         NaN            NaN

In [71]:
copy = df.sort_values(['Data Structure Marks','Python Marks'])
print(copy)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
8     PH1009        Omar Faruq                  72.0             72.0
5     PH1006       Laila Begum                  75.0             75.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
11    PH1012   Sadia Chowdhury                  85.0             85.0
14    PH1015      Wahiduzzaman                  86.0             86.0
19    PH1020        Nasir Khan                  86.0             86.0
17    PH1018       Babul Ahmed                  88.0             88.0
2     PH1003     Imran Hossain                  88.0             88.0
9     PH1010      Priya Sharma                  89.0             89.0
16    PH1017       Afsana Mimi                  90.0             90.0
1     PH1002     Fatima Akhter                  92.0             92.0
15    PH1016      Ziaur Rahman                  94.0             94.0
10    PH1011      Rahim Sheikh                   NaN              NaN
4     PH1005       Kamal Uddin                   NaN              NaN
13    PH1014        Urmi Akter                   NaN              NaN
18    PH1019      Faria Rahman                   NaN              NaN
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
8           76.0        Completed     2024-05-16       Dhaka            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
3           86.0        Completed     2024-02-12      Sylhet            NaN
6            NaN      In Progress     2024-04-01       Dhaka            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
2           89.0        Completed     2024-02-10       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
16          93.0        Completed     2025-09-01       Dhaka            NaN
1           99.0        Completed     2024-01-20  Chattogram           95.0
15           NaN      In Progress     2024-08-21  Chattogram            NaN
10          91.0      In Progress     2024-06-11      Khulna            NaN
4           95.0      In Progress     2024-03-05  Chattogram            NaN
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN
0            NaN        Completed            NaN         NaN            NaN

In [72]:
nnew = df.sort_values(['Data Structure Marks','Python Marks'],ascending = [0,1])
print(nnew)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
15    PH1016      Ziaur Rahman                  94.0             94.0
1     PH1002     Fatima Akhter                  92.0             92.0
16    PH1017       Afsana Mimi                  90.0             90.0
9     PH1010      Priya Sharma                  89.0             89.0
17    PH1018       Babul Ahmed                  88.0             88.0
2     PH1003     Imran Hossain                  88.0             88.0
14    PH1015      Wahiduzzaman                  86.0             86.0
19    PH1020        Nasir Khan                  86.0             86.0
11    PH1012   Sadia Chowdhury                  85.0             85.0
7     PH1008       Nadia Islam                  81.0             81.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
5     PH1006       Laila Begum                  75.0             75.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
8     PH1009        Omar Faruq                  72.0             72.0
10    PH1011      Rahim Sheikh                   NaN              NaN
4     PH1005       Kamal Uddin                   NaN              NaN
13    PH1014        Urmi Akter                   NaN              NaN
18    PH1019      Faria Rahman                   NaN              NaN
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
15           NaN      In Progress     2024-08-21  Chattogram            NaN
1           99.0        Completed     2024-01-20  Chattogram           95.0
16          93.0        Completed     2025-09-01       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
2           89.0        Completed     2024-02-10       Dhaka            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
6            NaN      In Progress     2024-04-01       Dhaka            NaN
3           86.0        Completed     2024-02-12      Sylhet            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
8           76.0        Completed     2024-05-16       Dhaka            NaN
10          91.0      In Progress     2024-06-11      Khulna            NaN
4           95.0      In Progress     2024-03-05  Chattogram            NaN
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN
0            NaN        Completed            NaN         NaN            NaN

#Filtering data based on Conditions

In [73]:
not_started = df.loc[df['CompletionStatus']== 'Not Started']
print(not_started)

   StudentID      FullName  Data Structure Marks  Algorithm Marks  \
13    PH1014    Urmi Akter                   NaN              NaN
18    PH1019  Faria Rahman                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
13           NaN      Not Started     2024-07-09    Rajshahi            NaN
18           NaN      Not Started     2025-09-15  Chattogram            NaN

In [75]:
completed = df.loc[df['CompletionStatus']== 'Completed']
print(completed)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
5     PH1006       Laila Begum                  75.0             75.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
14    PH1015      Wahiduzzaman                  86.0             86.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
19    PH1020        Nasir Khan                  86.0             86.0
0        NaN               NaN                   NaN              NaN

    Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
1           99.0        Completed     2024-01-20  Chattogram           95.0
2           89.0        Completed     2024-02-10       Dhaka            NaN
3           86.0        Completed     2024-02-12      Sylhet            NaN
5           78.0        Completed     2024-03-08    Rajshahi            NaN
7           85.0        Completed     2024-04-22  Chattogram            NaN
8           76.0        Completed     2024-05-16       Dhaka            NaN
9           88.0        Completed     2024-05-20      Sylhet            NaN
11          87.0        Completed     2024-06-14  Chattogram            NaN
12          79.0        Completed     2024-07-02       Dhaka            NaN
14          84.0        Completed     2024-08-18       Dhaka            NaN
16          93.0        Completed     2025-09-01       Dhaka            NaN
17          85.0        Completed     2025-09-05      Sylhet            NaN
19          89.0        Completed     2025-10-02       Dhaka            NaN
0            NaN        Completed            NaN         NaN            NaN

In [77]:
more_than_90 = df.loc[(df['Data Structure Marks'] > 90) & (df['CompletionStatus'] == 'Completed')]
print(more_than_90)

  StudentID       FullName  Data Structure Marks  Algorithm Marks  \
1    PH1002  Fatima Akhter                  92.0             92.0

   Python Marks CompletionStatus EnrollmentDate    Location  Python Marks
1          99.0        Completed     2024-01-20  Chattogram           95.0