In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

In [2]:
print(df)

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [3]:
#to find out if New exists in the city column at any place
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [4]:
#to find out if it captures with small letter, which is not possible obviously
df.loc[df['City'].str.contains("new")]

Empty DataFrame
Columns: [Name, City, Department, Salary]
Index: []

In [5]:
#now by using case attribute, we are telling the dataset about it doesn't matter whether its written on capital or small letter
df.loc[df['City'].str.contains("new", case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [6]:
#to find out if Los exists in the beggining of the string
df.loc[df['City'].str.contains("^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [7]:
#to find out if rk exists in the end of the string
df.loc[df['City'].str.contains(f"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [8]:
#if name exists with vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [9]:
#string Contains New or Los
df.loc[df['City'].str.contains(f"New | Los")]

    Name         City Department  Salary
0  Alice     New York         HR   50000
4    Eve    New Delhi         HR   52000
6  Grace  New Orleans    Finance   62000
8  Sakib    H Los Ang         HR   70000

In [10]:
df = pd.read_csv("/content/student_completed_data.csv")

In [11]:
print(df)

   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate  \
0     PH0001       Alif Rahman        Completed     2024-09-01   2024-12-23
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07
2     PH0003     Imran Hossain        Completed     2024-05-08   2024-08-08
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23
4     PH0005       Kamal Uddin        Completed     2024-02-01   2024-04-17
5     PH0006       Laila Begum        Completed     2024-09-07   2024-12-31
6     PH0007    Mahmudul Hasan        Completed     2024-06-07   2024-07-20
7     PH0008       Nadia Islam        Completed     2024-03-22   2024-05-01
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08
9     PH0010      Priya Sharma        Completed     2024-06-19   2024-08-19
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25
12    PH0013      Tanvir Ahmed        Completed     2024-06-07   2024-08-03
13    PH0014        Urmi Akter        Completed     2024-01-04   2024-03-23
14    PH0015      Wahiduzzaman        Completed     2024-02-22   2024-05-16
15    PH0016      Ziaur Rahman        Completed     2024-03-23   2024-06-21
16    PH0017       Afsana Mimi        Completed     2024-01-18   2024-03-16
17    PH0018       Babul Ahmed        Completed     2024-06-23   2024-09-20
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11

   Instructor    Location  Total Marks
0   Ms. Salma      Khulna          300
1   Mr. Karim       Dhaka          271
2   Ms. Salma       Dhaka          269
3   Mr. Karim      Khulna          270
4   Mr. David      Sylhet          254
5   Mr. David      Khulna          272
6   Mr. David  Chattogram          249
7   Ms. Salma      Khulna          246
8   Mr. Karim       Dhaka          291
9   Mr. David       Dhaka          286
10  Mr. Karim      Sylhet          283
11  Mr. Karim      Sylhet          266
12  Mr. David       Dhaka          248
13  Mr. David      Sylhet          285
14  Mr. David    Rajshahi          291
15  Ms. Salma    Rajshahi          234
16  Mr. David      Khulna          236
17  Mr. David       Dhaka          278
18  Mr. Karim      Sylhet          277
19  Mr. Karim      Khulna          253

In [12]:
#adding a column with constant value
df['country'] = "Bangladesh"
print(df)

   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate  \
0     PH0001       Alif Rahman        Completed     2024-09-01   2024-12-23
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07
2     PH0003     Imran Hossain        Completed     2024-05-08   2024-08-08
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23
4     PH0005       Kamal Uddin        Completed     2024-02-01   2024-04-17
5     PH0006       Laila Begum        Completed     2024-09-07   2024-12-31
6     PH0007    Mahmudul Hasan        Completed     2024-06-07   2024-07-20
7     PH0008       Nadia Islam        Completed     2024-03-22   2024-05-01
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08
9     PH0010      Priya Sharma        Completed     2024-06-19   2024-08-19
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25
12    PH0013      Tanvir Ahmed        Completed     2024-06-07   2024-08-03
13    PH0014        Urmi Akter        Completed     2024-01-04   2024-03-23
14    PH0015      Wahiduzzaman        Completed     2024-02-22   2024-05-16
15    PH0016      Ziaur Rahman        Completed     2024-03-23   2024-06-21
16    PH0017       Afsana Mimi        Completed     2024-01-18   2024-03-16
17    PH0018       Babul Ahmed        Completed     2024-06-23   2024-09-20
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11

   Instructor    Location  Total Marks     country
0   Ms. Salma      Khulna          300  Bangladesh
1   Mr. Karim       Dhaka          271  Bangladesh
2   Ms. Salma       Dhaka          269  Bangladesh
3   Mr. Karim      Khulna          270  Bangladesh
4   Mr. David      Sylhet          254  Bangladesh
5   Mr. David      Khulna          272  Bangladesh
6   Mr. David  Chattogram          249  Bangladesh
7   Ms. Salma      Khulna          246  Bangladesh
8   Mr. Karim       Dhaka          291  Bangladesh
9   Mr. David       Dhaka          286  Bangladesh
10  Mr. Karim      Sylhet          283  Bangladesh
11  Mr. Karim      Sylhet          266  Bangladesh
12  Mr. David       Dhaka          248  Bangladesh
13  Mr. David      Sylhet          285  Bangladesh
14  Mr. David    Rajshahi          291  Bangladesh
15  Ms. Salma    Rajshahi          234  Bangladesh
16  Mr. David      Khulna          236  Bangladesh
17  Mr. David       Dhaka          278  Bangladesh
18  Mr. Karim      Sylhet          277  Bangladesh
19  Mr. Karim      Khulna          253  Bangladesh

In [13]:
import numpy as np

In [14]:
df['Data Structure Marks'] = np.random.randint(45,100, size =len(df))
df['Algorithm Marks'] = np.random.randint(45,100, size = len(df))
df['Python Marks'] = np.random.randint(45,100, size = len(df))

In [15]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,country,Data Structure Marks,Algorithm Marks,Python Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,Bangladesh,73,92,99
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,Bangladesh,45,64,46
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,Bangladesh,71,66,66
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,Bangladesh,93,56,85
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,Bangladesh,88,53,47
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,Bangladesh,90,81,87
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,Bangladesh,97,74,77
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,Bangladesh,84,83,96
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,Bangladesh,68,45,47
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,Bangladesh,79,89,70
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,Bangladesh,50,53,63
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,Bangladesh,71,68,72
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,Bangladesh,76,53,79
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,Bangladesh,82,65,73
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,Bangladesh,97,68,86
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,Bangladesh,54,67,57
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,Bangladesh,50,45,56
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,Bangladesh,75,50,77
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,Bangladesh,67,50,94
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,Bangladesh,97,48,79

In [16]:
df['Total Marks'] = df['Data Structure Marks'] + df['Python Marks'] + df['Algorithm Marks']
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,country,Data Structure Marks,Algorithm Marks,Python Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,264,Bangladesh,73,92,99
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,155,Bangladesh,45,64,46
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,203,Bangladesh,71,66,66
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,234,Bangladesh,93,56,85
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,188,Bangladesh,88,53,47
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,258,Bangladesh,90,81,87
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,248,Bangladesh,97,74,77
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,263,Bangladesh,84,83,96
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,160,Bangladesh,68,45,47
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,238,Bangladesh,79,89,70
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,166,Bangladesh,50,53,63
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,211,Bangladesh,71,68,72
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,208,Bangladesh,76,53,79
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,220,Bangladesh,82,65,73
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,251,Bangladesh,97,68,86
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,178,Bangladesh,54,67,57
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,151,Bangladesh,50,45,56
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,202,Bangladesh,75,50,77
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,211,Bangladesh,67,50,94
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,224,Bangladesh,97,48,79

In [17]:
df['A+ in DS'] = np.where(df['Data Structure Marks'] > 95, "A+", "A")
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,country,Data Structure Marks,Algorithm Marks,Python Marks,A+ in DS
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,264,Bangladesh,73,92,99,A
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,155,Bangladesh,45,64,46,A
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,203,Bangladesh,71,66,66,A
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,234,Bangladesh,93,56,85,A
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,188,Bangladesh,88,53,47,A
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,258,Bangladesh,90,81,87,A
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,248,Bangladesh,97,74,77,A+
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,263,Bangladesh,84,83,96,A
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,160,Bangladesh,68,45,47,A
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,238,Bangladesh,79,89,70,A
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,166,Bangladesh,50,53,63,A
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,211,Bangladesh,71,68,72,A
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,208,Bangladesh,76,53,79,A
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,220,Bangladesh,82,65,73,A
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,251,Bangladesh,97,68,86,A+
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,178,Bangladesh,54,67,57,A
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,151,Bangladesh,50,45,56,A
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,202,Bangladesh,75,50,77,A
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,211,Bangladesh,67,50,94,A
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,224,Bangladesh,97,48,79,A+

In [18]:
df['Passed in Algorithm'] = df['Algorithm Marks'] > 65
print(df)

   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate  \
0     PH0001       Alif Rahman        Completed     2024-09-01   2024-12-23
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07
2     PH0003     Imran Hossain        Completed     2024-05-08   2024-08-08
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23
4     PH0005       Kamal Uddin        Completed     2024-02-01   2024-04-17
5     PH0006       Laila Begum        Completed     2024-09-07   2024-12-31
6     PH0007    Mahmudul Hasan        Completed     2024-06-07   2024-07-20
7     PH0008       Nadia Islam        Completed     2024-03-22   2024-05-01
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08
9     PH0010      Priya Sharma        Completed     2024-06-19   2024-08-19
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25
12    PH0013      Tanvir Ahmed        Completed     2024-06-07   2024-08-03
13    PH0014        Urmi Akter        Completed     2024-01-04   2024-03-23
14    PH0015      Wahiduzzaman        Completed     2024-02-22   2024-05-16
15    PH0016      Ziaur Rahman        Completed     2024-03-23   2024-06-21
16    PH0017       Afsana Mimi        Completed     2024-01-18   2024-03-16
17    PH0018       Babul Ahmed        Completed     2024-06-23   2024-09-20
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11

   Instructor    Location  Total Marks     country  Data Structure Marks  \
0   Ms. Salma      Khulna          264  Bangladesh                    73
1   Mr. Karim       Dhaka          155  Bangladesh                    45
2   Ms. Salma       Dhaka          203  Bangladesh                    71
3   Mr. Karim      Khulna          234  Bangladesh                    93
4   Mr. David      Sylhet          188  Bangladesh                    88
5   Mr. David      Khulna          258  Bangladesh                    90
6   Mr. David  Chattogram          248  Bangladesh                    97
7   Ms. Salma      Khulna          263  Bangladesh                    84
8   Mr. Karim       Dhaka          160  Bangladesh                    68
9   Mr. David       Dhaka          238  Bangladesh                    79
10  Mr. Karim      Sylhet          166  Bangladesh                    50
11  Mr. Karim      Sylhet          211  Bangladesh                    71
12  Mr. David       Dhaka          208  Bangladesh                    76
13  Mr. David      Sylhet          220  Bangladesh                    82
14  Mr. David    Rajshahi          251  Bangladesh                    97
15  Ms. Salma    Rajshahi          178  Bangladesh                    54
16  Mr. David      Khulna          151  Bangladesh                    50
17  Mr. David       Dhaka          202  Bangladesh                    75
18  Mr. Karim      Sylhet          211  Bangladesh                    67
19  Mr. Karim      Khulna          224  Bangladesh                    97

    Algorithm Marks  Python Marks A+ in DS  Passed in Algorithm
0                92            99        A                 True
1                64            46        A                False
2                66            66        A                 True
3                56            85        A                False
4                53            47        A                False
5                81            87        A                 True
6                74            77       A+                 True
7                83            96        A                 True
8                45            47        A                False
9                89            70        A                 True
10               53            63        A                False
11               68            72        A                 True
12               53            79        A                False
13               65            73        A                False
14               68            86       A+                 True
15               67            57        A                 True
16               45            56        A                False
17               50            77        A                False
18               50            94        A                False
19               48            79       A+                False

In [19]:
df['First Name'] = df['FullName'].str.split(' ').str[0]

In [20]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,country,Data Structure Marks,Algorithm Marks,Python Marks,A+ in DS,Passed in Algorithm,First Name
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,264,Bangladesh,73,92,99,A,True,Alif
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,155,Bangladesh,45,64,46,A,False,Fatima
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,203,Bangladesh,71,66,66,A,True,Imran
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,234,Bangladesh,93,56,85,A,False,Jannatul
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,188,Bangladesh,88,53,47,A,False,Kamal
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,258,Bangladesh,90,81,87,A,True,Laila
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,248,Bangladesh,97,74,77,A+,True,Mahmudul
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,263,Bangladesh,84,83,96,A,True,Nadia
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,160,Bangladesh,68,45,47,A,False,Omar
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,238,Bangladesh,79,89,70,A,True,Priya
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,166,Bangladesh,50,53,63,A,False,Rahim
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,211,Bangladesh,71,68,72,A,True,Sadia
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,208,Bangladesh,76,53,79,A,False,Tanvir
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,220,Bangladesh,82,65,73,A,False,Urmi
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,251,Bangladesh,97,68,86,A+,True,Wahiduzzaman
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,178,Bangladesh,54,67,57,A,True,Ziaur
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,151,Bangladesh,50,45,56,A,False,Afsana
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,202,Bangladesh,75,50,77,A,False,Babul
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,211,Bangladesh,67,50,94,A,False,Faria
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,224,Bangladesh,97,48,79,A+,False,Tariq

In [21]:
df1 = pd.read_csv('/content/student_completed_data.csv')

In [22]:
df1

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [23]:
df.to_csv('updated sheet.csv')

In [24]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [25]:
df['Name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David'], dtype=object)

In [26]:
df['Name'].nunique()

4

In [27]:
df1 = pd.read_csv('/content/updated sheet.csv')

In [28]:
df1

,Unnamed: 0,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,country,Data Structure Marks,Algorithm Marks,Python Marks,A+ in DS,Passed in Algorithm,First Name
0,0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,264,Bangladesh,73,92,99,A,True,Alif
1,1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,155,Bangladesh,45,64,46,A,False,Fatima
2,2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,203,Bangladesh,71,66,66,A,True,Imran
3,3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,234,Bangladesh,93,56,85,A,False,Jannatul
4,4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,188,Bangladesh,88,53,47,A,False,Kamal
5,5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,258,Bangladesh,90,81,87,A,True,Laila
6,6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,248,Bangladesh,97,74,77,A+,True,Mahmudul
7,7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,263,Bangladesh,84,83,96,A,True,Nadia
8,8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,160,Bangladesh,68,45,47,A,False,Omar
9,9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,238,Bangladesh,79,89,70,A,True,Priya
10,10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,166,Bangladesh,50,53,63,A,False,Rahim
11,11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,211,Bangladesh,71,68,72,A,True,Sadia
12,12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,208,Bangladesh,76,53,79,A,False,Tanvir
13,13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,220,Bangladesh,82,65,73,A,False,Urmi
14,14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,251,Bangladesh,97,68,86,A+,True,Wahiduzzaman
15,15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,178,Bangladesh,54,67,57,A,True,Ziaur
16,16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,151,Bangladesh,50,45,56,A,False,Afsana
17,17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,202,Bangladesh,75,50,77,A,False,Babul
18,18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,211,Bangladesh,67,50,94,A,False,Faria
19,19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,224,Bangladesh,97,48,79,A+,False,Tariq

In [29]:
len(df1['Data Structure Marks'].unique())

16

In [30]:
df1['Data Structure Marks'].nunique()

16

In [31]:
df1.isnull()

,Unnamed: 0,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,country,Data Structure Marks,Algorithm Marks,Python Marks,A+ in DS,Passed in Algorithm,First Name
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [32]:
df1['Data Structure Marks'].hasnans

False

In [33]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}
df = pd.DataFrame(data)
print(df)

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [34]:
df.drop_duplicates(inplace = True)

In [35]:
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [36]:
df.drop_duplicates(subset = ['Name'] ,inplace = True)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [37]:
df.drop_duplicates(subset = ['City'] ,inplace = True)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [38]:
df = pd.read_csv('/content/student_completed_data.csv')
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [39]:
df = pd.read_csv('/content/sheets.csv')
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [40]:
df.dropna()

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [41]:
df.dropna(how ='all', inplace = True)
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [42]:
df.dropna(subset = ['Python Marks'], inplace = True)
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [43]:
sub = df.dropna(subset = ['Data Structure Marks','Algorithm Marks'])

In [44]:
print(sub)

    Unnamed: 0 StudentID          FullName  Data Structure Marks  \
0            0    PH1001       Alif Rahman                  85.0
2            2    PH1003     Imran Hossain                  88.0
3            3    PH1004  Jannatul Ferdous                  78.0
5            5    PH1006       Laila Begum                  75.0
7            7    PH1008       Nadia Islam                  81.0
8            8    PH1009        Omar Faruq                  72.0
9            9    PH1010      Priya Sharma                  89.0
11          11    PH1012   Sadia Chowdhury                  85.0
12          12    PH1013      Tanvir Ahmed                  75.0
14          14    PH1015      Wahiduzzaman                  86.0
16          16    PH1017       Afsana Mimi                  90.0
17          17    PH1018       Babul Ahmed                  88.0
19          19    PH1020        Nasir Khan                  86.0

    Algorithm Marks  Python Marks CompletionStatus EnrollmentDate Instructor  \
0              85.0          88.0        Completed     2024-01-15  Mr. Karim
2              88.0          85.0        Completed     2024-02-10  Mr. Karim
3              78.0          82.0        Completed     2024-02-12  Ms. Salma
5              75.0          78.0        Completed     2024-03-08  Ms. Salma
7              81.0          85.0        Completed     2024-04-22  Ms. Salma
8              72.0          76.0        Completed     2024-05-16  Mr. David
9              89.0          88.0        Completed     2024-05-20  Ms. Salma
11             85.0          87.0        Completed     2024-06-14  Ms. Salma
12             75.0          79.0        Completed     2024-07-02  Mr. David
14             86.0          84.0        Completed     2024-08-18  Mr. Karim
16             90.0          93.0        Completed     2025-09-01  Mr. Karim
17             88.0          85.0        Completed     2025-09-05  Ms. Salma
19             86.0          89.0        Completed     2025-10-02  Ms. Salma

      Location     Country  Total Marks A+ in DS  Passed in DS    First Name
0        Dhaka  Bangladesh        258.0        A          True          Alif
2        Dhaka  Bangladesh        261.0        A          True         Imran
3       Sylhet  Bangladesh        238.0        A          True      Jannatul
5     Rajshahi  Bangladesh        228.0        A          True         Laila
7   Chattogram  Bangladesh        247.0        A          True         Nadia
8        Dhaka  Bangladesh        220.0        A          True          Omar
9       Sylhet  Bangladesh        266.0        A          True         Priya
11  Chattogram  Bangladesh        257.0        A          True         Sadia
12       Dhaka  Bangladesh        229.0        A          True        Tanvir
14       Dhaka  Bangladesh        256.0        A          True  Wahiduzzaman
16       Dhaka  Bangladesh        273.0        A          True        Afsana
17      Sylhet  Bangladesh        261.0        A          True         Babul
19       Dhaka  Bangladesh        261.0        A          True         Nasir

In [45]:
df.fillna(0)

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,0.0,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,0.0,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [46]:
df = pd.read_csv('/content/sheets.csv')
print(df)

    Unnamed: 0 StudentID          FullName  Data Structure Marks  \
0            0    PH1001       Alif Rahman                  85.0
1            1    PH1002     Fatima Akhter                  92.0
2            2    PH1003     Imran Hossain                  88.0
3            3    PH1004  Jannatul Ferdous                  78.0
4            4    PH1005       Kamal Uddin                   NaN
5            5    PH1006       Laila Begum                  75.0
6            6    PH1007    Mahmudul Hasan                  80.0
7            7    PH1008       Nadia Islam                  81.0
8            8    PH1009        Omar Faruq                  72.0
9            9    PH1010      Priya Sharma                  89.0
10          10    PH1011      Rahim Sheikh                   NaN
11          11    PH1012   Sadia Chowdhury                  85.0
12          12    PH1013      Tanvir Ahmed                  75.0
13          13    PH1014        Urmi Akter                   NaN
14          14    PH1015      Wahiduzzaman                  86.0
15          15    PH1016      Ziaur Rahman                  94.0
16          16    PH1017       Afsana Mimi                  90.0
17          17    PH1018       Babul Ahmed                  88.0
18          18    PH1019      Faria Rahman                   NaN
19          19    PH1020        Nasir Khan                  86.0

    Algorithm Marks  Python Marks CompletionStatus EnrollmentDate Instructor  \
0              85.0          88.0        Completed     2024-01-15  Mr. Karim
1              92.0           NaN      In Progress     2024-01-20  Ms. Salma
2              88.0          85.0        Completed     2024-02-10  Mr. Karim
3              78.0          82.0        Completed     2024-02-12  Ms. Salma
4               NaN          95.0      In Progress     2024-03-05  Mr. Karim
5              75.0          78.0        Completed     2024-03-08  Ms. Salma
6              80.0           NaN      In Progress     2024-04-01  Mr. Karim
7              81.0          85.0        Completed     2024-04-22  Ms. Salma
8              72.0          76.0        Completed     2024-05-16  Mr. David
9              89.0          88.0        Completed     2024-05-20  Ms. Salma
10              NaN          91.0      In Progress     2024-06-11  Mr. Karim
11             85.0          87.0        Completed     2024-06-14  Ms. Salma
12             75.0          79.0        Completed     2024-07-02  Mr. David
13              NaN           NaN      Not Started     2024-07-09  Ms. Salma
14             86.0          84.0        Completed     2024-08-18  Mr. Karim
15             94.0           NaN      In Progress     2024-08-21  Ms. Salma
16             90.0          93.0        Completed     2025-09-01  Mr. Karim
17             88.0          85.0        Completed     2025-09-05  Ms. Salma
18              NaN           NaN      Not Started     2025-09-15  Mr. David
19             86.0          89.0        Completed     2025-10-02  Ms. Salma

      Location     Country  Total Marks A+ in DS  Passed in DS    First Name
0        Dhaka  Bangladesh        258.0        A          True          Alif
1   Chattogram  Bangladesh          NaN       A+          True        Fatima
2        Dhaka  Bangladesh        261.0        A          True         Imran
3       Sylhet  Bangladesh        238.0        A          True      Jannatul
4   Chattogram  Bangladesh          NaN        A         False         Kamal
5     Rajshahi  Bangladesh        228.0        A          True         Laila
6        Dhaka  Bangladesh          NaN        A          True      Mahmudul
7   Chattogram  Bangladesh        247.0        A          True         Nadia
8        Dhaka  Bangladesh        220.0        A          True          Omar
9       Sylhet  Bangladesh        266.0        A          True         Priya
10      Khulna  Bangladesh          NaN        A         False         Rahim
11  Chattogram  Bangladesh        257.0        A          True         Sadia
12       Dhaka  Bangladesh        229.0        A          True        Tanvir
13    Rajshahi  Bangladesh          NaN        A         False          Urmi
14       Dhaka  Bangladesh        256.0        A          True  Wahiduzzaman
15  Chattogram  Bangladesh          NaN       A+          True         Ziaur
16       Dhaka  Bangladesh        273.0        A          True        Afsana
17      Sylhet  Bangladesh        261.0        A          True         Babul
18  Chattogram  Bangladesh          NaN        A         False         Faria
19       Dhaka  Bangladesh        261.0        A          True         Nasir

In [47]:
df.fillna(0)

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,0.0,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,0.0,A+,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,0.0,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,0.0,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,0.0,A,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,0.0,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,13,PH1014,Urmi Akter,0.0,0.0,0.0,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,0.0,A,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,0.0,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,0.0,A+,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,18,PH1019,Faria Rahman,0.0,0.0,0.0,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,0.0,A,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [48]:
df['FullName'].fillna("Papi Bilota")
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [49]:
df['Python Marks'].fillna(df['Python Marks'].mean(), inplace = True)
print(df)

    Unnamed: 0 StudentID          FullName  Data Structure Marks  \
0            0    PH1001       Alif Rahman                  85.0
1            1    PH1002     Fatima Akhter                  92.0
2            2    PH1003     Imran Hossain                  88.0
3            3    PH1004  Jannatul Ferdous                  78.0
4            4    PH1005       Kamal Uddin                   NaN
5            5    PH1006       Laila Begum                  75.0
6            6    PH1007    Mahmudul Hasan                  80.0
7            7    PH1008       Nadia Islam                  81.0
8            8    PH1009        Omar Faruq                  72.0
9            9    PH1010      Priya Sharma                  89.0
10          10    PH1011      Rahim Sheikh                   NaN
11          11    PH1012   Sadia Chowdhury                  85.0
12          12    PH1013      Tanvir Ahmed                  75.0
13          13    PH1014        Urmi Akter                   NaN
14          14    PH1015      Wahiduzzaman                  86.0
15          15    PH1016      Ziaur Rahman                  94.0
16          16    PH1017       Afsana Mimi                  90.0
17          17    PH1018       Babul Ahmed                  88.0
18          18    PH1019      Faria Rahman                   NaN
19          19    PH1020        Nasir Khan                  86.0

    Algorithm Marks  Python Marks CompletionStatus EnrollmentDate Instructor  \
0              85.0     88.000000        Completed     2024-01-15  Mr. Karim
1              92.0     85.666667      In Progress     2024-01-20  Ms. Salma
2              88.0     85.000000        Completed     2024-02-10  Mr. Karim
3              78.0     82.000000        Completed     2024-02-12  Ms. Salma
4               NaN     95.000000      In Progress     2024-03-05  Mr. Karim
5              75.0     78.000000        Completed     2024-03-08  Ms. Salma
6              80.0     85.666667      In Progress     2024-04-01  Mr. Karim
7              81.0     85.000000        Completed     2024-04-22  Ms. Salma
8              72.0     76.000000        Completed     2024-05-16  Mr. David
9              89.0     88.000000        Completed     2024-05-20  Ms. Salma
10              NaN     91.000000      In Progress     2024-06-11  Mr. Karim
11             85.0     87.000000        Completed     2024-06-14  Ms. Salma
12             75.0     79.000000        Completed     2024-07-02  Mr. David
13              NaN     85.666667      Not Started     2024-07-09  Ms. Salma
14             86.0     84.000000        Completed     2024-08-18  Mr. Karim
15             94.0     85.666667      In Progress     2024-08-21  Ms. Salma
16             90.0     93.000000        Completed     2025-09-01  Mr. Karim
17             88.0     85.000000        Completed     2025-09-05  Ms. Salma
18              NaN     85.666667      Not Started     2025-09-15  Mr. David
19             86.0     89.000000        Completed     2025-10-02  Ms. Salma

      Location     Country  Total Marks A+ in DS  Passed in DS    First Name
0        Dhaka  Bangladesh        258.0        A          True          Alif
1   Chattogram  Bangladesh          NaN       A+          True        Fatima
2        Dhaka  Bangladesh        261.0        A          True         Imran
3       Sylhet  Bangladesh        238.0        A          True      Jannatul
4   Chattogram  Bangladesh          NaN        A         False         Kamal
5     Rajshahi  Bangladesh        228.0        A          True         Laila
6        Dhaka  Bangladesh          NaN        A          True      Mahmudul
7   Chattogram  Bangladesh        247.0        A          True         Nadia
8        Dhaka  Bangladesh        220.0        A          True          Omar
9       Sylhet  Bangladesh        266.0        A          True         Priya
10      Khulna  Bangladesh          NaN        A         False         Rahim
11  Chattogram  Bangladesh        257.0        A          True         Sadia
12       Dhaka  Bangladesh        229.0        A          True        Tanvir
13    Rajshahi  Bangladesh          NaN        A         False          Urmi
14       Dhaka  Bangladesh        256.0        A          True  Wahiduzzaman
15  Chattogram  Bangladesh          NaN       A+          True         Ziaur
16       Dhaka  Bangladesh        273.0        A          True        Afsana
17      Sylhet  Bangladesh        261.0        A          True         Babul
18  Chattogram  Bangladesh          NaN        A         False         Faria
19       Dhaka  Bangladesh        261.0        A          True         Nasir

/tmp/ipykernel_1038/2651883958.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean(), inplace = True)

In [50]:
df['Data Structure Marks'].sum()

np.float64(1344.0)

In [51]:
a = df['Data Structure Marks'].min()
b = df['Data Structure Marks'].max()
print(a)
print(b)

72.0
94.0

In [52]:
df['Algorithm Marks'].median()

85.5

In [53]:
df['Algorithm Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Algorithm Marks, dtype: float64

In [54]:
df['Data Structure Marks'].std()

6.501281924871945

In [55]:
df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.776845
Python Marks                      0.776845      1.000000

In [56]:
 df[['Data Structure Marks','Python Marks']].sum(axis = 1)

0     173.000000
1     177.666667
2     173.000000
3     160.000000
4      95.000000
5     153.000000
6     165.666667
7     166.000000
8     148.000000
9     177.000000
10     91.000000
11    172.000000
12    154.000000
13     85.666667
14    170.000000
15    179.666667
16    183.000000
17    173.000000
18     85.666667
19    175.000000
dtype: float64

In [57]:
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir
13,13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul
18,18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir

In [58]:
df['Tottal Marks'] = df.iloc[::,3:6].sum(axis = 1)
df['Tottal Marks']

0     258.000000
1     269.666667
2     261.000000
3     238.000000
4      95.000000
5     228.000000
6     245.666667
7     247.000000
8     220.000000
9     266.000000
10     91.000000
11    257.000000
12    229.000000
13     85.666667
14    256.000000
15    273.666667
16    273.000000
17    261.000000
18     85.666667
19    261.000000
Name: Tottal Marks, dtype: float64

In [59]:
df.describe()

,Unnamed: 0,Data Structure Marks,Algorithm Marks,Python Marks,Total Marks,Tottal Marks
count,20.00000,16.000000,16.000000,20.000000,13.000000,20.000000
mean,9.50000,84.000000,84.000000,85.666667,250.384615,220.066667
std,5.91608,6.501282,6.501282,4.630183,16.515339,68.685962
min,0.00000,72.000000,72.000000,76.000000,220.000000,85.666667
25%,4.75000,79.500000,79.500000,84.750000,238.000000,226.000000
50%,9.50000,85.500000,85.500000,85.666667,257.000000,251.500000
75%,14.25000,88.250000,88.250000,88.000000,261.000000,261.000000
max,19.00000,94.000000,94.000000,95.000000,273.000000,273.666667

In [60]:
mn = df['Total Marks'].min()
mx = df['Total Marks'].max()
df['Scaled Marks'] = df['Total Marks'].apply(lambda x: (x-mn)/(mx-mn))

In [61]:
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name,Tottal Marks,Scaled Marks
0,0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif,258.000000,0.716981
1,1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima,269.666667,NaN
2,2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran,261.000000,0.773585
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul,238.000000,0.339623
4,4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal,95.000000,NaN
5,5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila,228.000000,0.150943
6,6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul,245.666667,NaN
7,7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia,247.000000,0.509434
8,8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar,220.000000,0.000000
9,9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya,266.000000,0.867925
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim,91.000000,NaN
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia,257.000000,0.698113
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir,229.000000,0.169811
13,13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi,85.666667,NaN
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman,256.000000,0.679245
15,15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur,273.666667,NaN
16,16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana,273.000000,1.000000
17,17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul,261.000000,0.773585
18,18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria,85.666667,NaN
19,19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir,261.000000,0.773585

In [62]:
def grading_system(marks):
  if marks>260:
    return 'A+'
  elif marks>250:
    return 'A'
  else:
    return 'F'

df['Grade'] = df['Tottal Marks'].apply(grading_system)

In [63]:
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name,Tottal Marks,Scaled Marks,Grade
0,0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif,258.000000,0.716981,A
1,1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima,269.666667,NaN,A+
2,2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran,261.000000,0.773585,A+
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul,238.000000,0.339623,F
4,4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal,95.000000,NaN,F
5,5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila,228.000000,0.150943,F
6,6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul,245.666667,NaN,F
7,7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia,247.000000,0.509434,F
8,8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar,220.000000,0.000000,F
9,9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya,266.000000,0.867925,A+
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim,91.000000,NaN,F
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia,257.000000,0.698113,A
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir,229.000000,0.169811,F
13,13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi,85.666667,NaN,F
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman,256.000000,0.679245,A
15,15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur,273.666667,NaN,A+
16,16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana,273.000000,1.000000,A+
17,17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul,261.000000,0.773585,A+
18,18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria,85.666667,NaN,F
19,19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir,261.000000,0.773585,A+

In [64]:
def marking(df):
  a = df['Algorithm Marks'] *3
  b = df['Data Structure Marks'] * 3
  return a+b




df['Exceptional Marks'] = df.apply(marking,axis =1)

In [65]:
df

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passed in DS,First Name,Tottal Marks,Scaled Marks,Grade,Exceptional Marks
0,0,PH1001,Alif Rahman,85.0,85.0,88.000000,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A,True,Alif,258.000000,0.716981,A,510.0
1,1,PH1002,Fatima Akhter,92.0,92.0,85.666667,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima,269.666667,NaN,A+,552.0
2,2,PH1003,Imran Hossain,88.0,88.0,85.000000,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A,True,Imran,261.000000,0.773585,A+,528.0
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.000000,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,A,True,Jannatul,238.000000,0.339623,F,468.0
4,4,PH1005,Kamal Uddin,NaN,NaN,95.000000,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,A,False,Kamal,95.000000,NaN,F,NaN
5,5,PH1006,Laila Begum,75.0,75.0,78.000000,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,A,True,Laila,228.000000,0.150943,F,450.0
6,6,PH1007,Mahmudul Hasan,80.0,80.0,85.666667,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A,True,Mahmudul,245.666667,NaN,F,480.0
7,7,PH1008,Nadia Islam,81.0,81.0,85.000000,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A,True,Nadia,247.000000,0.509434,F,486.0
8,8,PH1009,Omar Faruq,72.0,72.0,76.000000,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,A,True,Omar,220.000000,0.000000,F,432.0
9,9,PH1010,Priya Sharma,89.0,89.0,88.000000,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A,True,Priya,266.000000,0.867925,A+,534.0
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.000000,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,A,False,Rahim,91.000000,NaN,F,NaN
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.000000,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A,True,Sadia,257.000000,0.698113,A,510.0
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.000000,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,A,True,Tanvir,229.000000,0.169811,F,450.0
13,13,PH1014,Urmi Akter,NaN,NaN,85.666667,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,A,False,Urmi,85.666667,NaN,F,NaN
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.000000,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A,True,Wahiduzzaman,256.000000,0.679245,A,516.0
15,15,PH1016,Ziaur Rahman,94.0,94.0,85.666667,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur,273.666667,NaN,A+,564.0
16,16,PH1017,Afsana Mimi,90.0,90.0,93.000000,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A,True,Afsana,273.000000,1.000000,A+,540.0
17,17,PH1018,Babul Ahmed,88.0,88.0,85.000000,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A,True,Babul,261.000000,0.773585,A+,528.0
18,18,PH1019,Faria Rahman,NaN,NaN,85.666667,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,A,False,Faria,85.666667,NaN,F,NaN
19,19,PH1020,Nasir Khan,86.0,86.0,89.000000,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A,True,Nasir,261.000000,0.773585,A+,516.0

In [66]:
df = pd.read_csv('/content/student_completed_data.csv')
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [67]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [68]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])

In [69]:
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [70]:
df['Enrollment_Year'] = df['EnrollmentDate'].dt.year

In [71]:
df['Enrollment_Day'] = df['EnrollmentDate'].dt.day

In [72]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])

In [73]:
df['Finish Year'] = df['FinishedDate'].dt.year
df['Finish Date'] = df['FinishedDate'].dt.day

In [75]:
df['Time Consumed'] = df['FinishedDate'] - df['EnrollmentDate']

In [76]:
print(df)

   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate  \
0     PH0001       Alif Rahman        Completed     2024-09-01   2024-12-23
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07
2     PH0003     Imran Hossain        Completed     2024-05-08   2024-08-08
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23
4     PH0005       Kamal Uddin        Completed     2024-02-01   2024-04-17
5     PH0006       Laila Begum        Completed     2024-09-07   2024-12-31
6     PH0007    Mahmudul Hasan        Completed     2024-06-07   2024-07-20
7     PH0008       Nadia Islam        Completed     2024-03-22   2024-05-01
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08
9     PH0010      Priya Sharma        Completed     2024-06-19   2024-08-19
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25
12    PH0013      Tanvir Ahmed        Completed     2024-06-07   2024-08-03
13    PH0014        Urmi Akter        Completed     2024-01-04   2024-03-23
14    PH0015      Wahiduzzaman        Completed     2024-02-22   2024-05-16
15    PH0016      Ziaur Rahman        Completed     2024-03-23   2024-06-21
16    PH0017       Afsana Mimi        Completed     2024-01-18   2024-03-16
17    PH0018       Babul Ahmed        Completed     2024-06-23   2024-09-20
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11

   Instructor    Location  Total Marks  Enrollment_Year  Enrollment_Day  \
0   Ms. Salma      Khulna          300             2024               1
1   Mr. Karim       Dhaka          271             2024              11
2   Ms. Salma       Dhaka          269             2024               8
3   Mr. Karim      Khulna          270             2024               5
4   Mr. David      Sylhet          254             2024               1
5   Mr. David      Khulna          272             2024               7
6   Mr. David  Chattogram          249             2024               7
7   Ms. Salma      Khulna          246             2024              22
8   Mr. Karim       Dhaka          291             2024              12
9   Mr. David       Dhaka          286             2024              19
10  Mr. Karim      Sylhet          283             2024              14
11  Mr. Karim      Sylhet          266             2024               4
12  Mr. David       Dhaka          248             2024               7
13  Mr. David      Sylhet          285             2024               4
14  Mr. David    Rajshahi          291             2024              22
15  Ms. Salma    Rajshahi          234             2024              23
16  Mr. David      Khulna          236             2024              18
17  Mr. David       Dhaka          278             2024              23
18  Mr. Karim      Sylhet          277             2024              19
19  Mr. Karim      Khulna          253             2024              21

    Finish Year  Finish Date Time Consumed
0          2024           23      113 days
1          2024            7       88 days
2          2024            8       92 days
3          2024           23       80 days
4          2024           17       76 days
5          2024           31      115 days
6          2024           20       43 days
7          2024            1       40 days
8          2024            8      117 days
9          2024           19       61 days
10         2024           11       89 days
11         2024           25       82 days
12         2024            3       57 days
13         2024           23       79 days
14         2024           16       84 days
15         2024           21       90 days
16         2024           16       58 days
17         2024           20       89 days
18         2024           17      120 days
19         2024           11       82 days

#group by functions in pandas

In [77]:
df = pd.read_csv("/content/student_completed_data.csv")
display(df)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [79]:
df.loc[df['FullName'] == 'Afsana Mimi', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Sadia Chowdhury', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Alif Rahman', 'Total Marks'] = np.nan
display(df)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0

In [81]:
instructor_group = df.groupby('Instructor')
for instructor,values in instructor_group:
  print(instructor)
  print(values)

Mr. David
   StudentID        FullName CompletionStatus EnrollmentDate FinishedDate  \
4     PH0005     Kamal Uddin        Completed     2024-02-01   2024-04-17
5     PH0006     Laila Begum        Completed     2024-09-07   2024-12-31
6     PH0007  Mahmudul Hasan        Completed     2024-06-07   2024-07-20
9     PH0010    Priya Sharma        Completed     2024-06-19   2024-08-19
12    PH0013    Tanvir Ahmed        Completed     2024-06-07   2024-08-03
13    PH0014      Urmi Akter        Completed     2024-01-04   2024-03-23
14    PH0015    Wahiduzzaman        Completed     2024-02-22   2024-05-16
16    PH0017     Afsana Mimi        Completed     2024-01-18   2024-03-16
17    PH0018     Babul Ahmed        Completed     2024-06-23   2024-09-20

   Instructor    Location  Total Marks
4   Mr. David      Sylhet        254.0
5   Mr. David      Khulna        272.0
6   Mr. David  Chattogram        249.0
9   Mr. David       Dhaka        286.0
12  Mr. David       Dhaka        248.0
13  Mr. David      Sylhet        285.0
14  Mr. David    Rajshahi        291.0
16  Mr. David      Khulna          NaN
17  Mr. David       Dhaka        278.0
Mr. Karim
   StudentID          FullName CompletionStatus EnrollmentDate FinishedDate  \
1     PH0002     Fatima Akhter        Completed     2024-08-11   2024-11-07
3     PH0004  Jannatul Ferdous        Completed     2024-07-05   2024-09-23
8     PH0009        Omar Faruq        Completed     2024-02-12   2024-06-08
10    PH0011      Rahim Sheikh        Completed     2024-03-14   2024-06-11
11    PH0012   Sadia Chowdhury        Completed     2024-08-04   2024-10-25
18    PH0019      Faria Rahman        Completed     2024-04-19   2024-08-17
19    PH0020       Tariq Hasan        Completed     2024-07-21   2024-10-11

   Instructor Location  Total Marks
1   Mr. Karim    Dhaka        271.0
3   Mr. Karim   Khulna        270.0
8   Mr. Karim    Dhaka        291.0
10  Mr. Karim   Sylhet        283.0
11  Mr. Karim   Sylhet          NaN
18  Mr. Karim   Sylhet        277.0
19  Mr. Karim   Khulna        253.0
Ms. Salma
   StudentID       FullName CompletionStatus EnrollmentDate FinishedDate  \
0     PH0001    Alif Rahman        Completed     2024-09-01   2024-12-23
2     PH0003  Imran Hossain        Completed     2024-05-08   2024-08-08
7     PH0008    Nadia Islam        Completed     2024-03-22   2024-05-01
15    PH0016   Ziaur Rahman        Completed     2024-03-23   2024-06-21

   Instructor  Location  Total Marks
0   Ms. Salma    Khulna          NaN
2   Ms. Salma     Dhaka        269.0
7   Ms. Salma    Khulna        246.0
15  Ms. Salma  Rajshahi        234.0

In [82]:
instructor_group.describe()

           Total Marks                                                       \
                 count        mean        std    min     25%    50%     75%
Instructor
Mr. David          8.0  270.375000  17.606310  248.0  252.75  275.0  285.25
Mr. Karim          6.0  274.166667  12.998718  253.0  270.25  274.0  281.50
Ms. Salma          3.0  249.666667  17.785762  234.0  240.00  246.0  257.50


              max
Instructor
Mr. David   291.0
Mr. Karim   291.0
Ms. Salma   269.0

In [85]:
mean_marks = instructor_group['Total Marks'].mean()
display(mean_marks)

Instructor
Mr. David    270.375000
Mr. Karim    274.166667
Ms. Salma    249.666667
Name: Total Marks, dtype: float64

In [86]:
df['Total Marks'] = df['Total Marks'].fillna(df['Instructor'].map(mean_marks))
display(df)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,249.666667
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.000000
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.000000
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.000000
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.000000
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.000000
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.000000
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.000000
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.000000
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.000000
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.000000
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,274.166667
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.000000
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.000000
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.000000
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.000000
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,270.375000
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.000000
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.000000
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.000000